# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tiny < Formula
  desc "Self-hosted AI agents on your own Kubernetes"
  homepage "https://tinysystems.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiny-systems/tiny/releases/download/v0.1.0/tiny_0.1.0_darwin_amd64.tar.gz"
      sha256 "c6abab14a6c1f26ee37092d0b6758e741613616c1d67703cf07b0906e39880d5"

      define_method(:install) do
        bin.install "tiny"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiny-systems/tiny/releases/download/v0.1.0/tiny_0.1.0_darwin_arm64.tar.gz"
      sha256 "370a34761253eb73bceaff337a8e8c4409ccfaad1559b04a046d6149605c0a38"

      define_method(:install) do
        bin.install "tiny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/tiny/releases/download/v0.1.0/tiny_0.1.0_linux_amd64.tar.gz"
      sha256 "b0dcd9ed633072c5fff4850c661245aa81aa034a3ce2597c38383724112ff394"
      define_method(:install) do
        bin.install "tiny"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/tiny/releases/download/v0.1.0/tiny_0.1.0_linux_arm64.tar.gz"
      sha256 "1a6a4223150bf09ff08fd55fbe3a1a3e81b930569f7e9ba9869e5a737540d71e"
      define_method(:install) do
        bin.install "tiny"
      end
    end
  end

  test do
    system "#{bin}/tiny", "--version"
  end
end
