# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpServer < Formula
  desc "Tiny Systems MCP server — local AI flow builder for Kubernetes"
  homepage "https://github.com/tiny-systems/mcp-server"
  version "0.2.0"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.2.0/mcp-server_darwin_amd64.tar.gz"
      sha256 "098dd58094dc395186fdbec067206a059072790688fe07435415a22a0f6040fe"

      define_method(:install) do
        bin.install "mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.2.0/mcp-server_darwin_arm64.tar.gz"
      sha256 "293861afd4bb99f1b51fa31855000b839669ecf34aa071ac1e8241f6e968e9d3"

      define_method(:install) do
        bin.install "mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.2.0/mcp-server_linux_amd64.tar.gz"
      sha256 "450670699904a00f814c72388251e7cb69169489e1ac327e6ad60a02a5a3728c"
      define_method(:install) do
        bin.install "mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.2.0/mcp-server_linux_arm64.tar.gz"
      sha256 "71444129c4bdde6cb58df633848c0a75880c6fcc3cab6beb3a1cef7bb88b28bd"
      define_method(:install) do
        bin.install "mcp-server"
      end
    end
  end

  test do
    assert_match "tinysystems", shell_output("#{bin}/mcp-server --help 2>&1", 0)
  end
end
