# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpServer < Formula
  desc "Tiny Systems MCP server — local AI flow builder for Kubernetes"
  homepage "https://github.com/tiny-systems/mcp-server"
  version "0.3.3"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.3.3/mcp-server_darwin_amd64.tar.gz"
      sha256 "9e2e825939720f0c62a28d474a533b3ee2b1d46b166b7a396554110aab88993b"

      define_method(:install) do
        bin.install "mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.3.3/mcp-server_darwin_arm64.tar.gz"
      sha256 "8b9e3e6e899cfc64e4a82ef9075742171e46e3723e91952cbfc96d43e356e1aa"

      define_method(:install) do
        bin.install "mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.3.3/mcp-server_linux_amd64.tar.gz"
      sha256 "6f154f01a5982e70c59f8d6c6a50f76b7e5f9157547c76ca957f59da69d662eb"
      define_method(:install) do
        bin.install "mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.3.3/mcp-server_linux_arm64.tar.gz"
      sha256 "f444879f98a1f1c799d41398b632157cfcfe76a956e837be6d7f45703bc8a422"
      define_method(:install) do
        bin.install "mcp-server"
      end
    end
  end

  test do
    assert_match "tinysystems", shell_output("#{bin}/mcp-server --help 2>&1", 0)
  end
end
