# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpServer < Formula
  desc "Tiny Systems MCP server — local AI flow builder for Kubernetes"
  homepage "https://github.com/tiny-systems/mcp-server"
  version "0.1.14"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.1.14/mcp-server_darwin_amd64.tar.gz"
      sha256 "d5aa16488e93e937fd0e889e1734b1d3255921261a9c79402ef585f186af7a1a"

      define_method(:install) do
        bin.install "mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.1.14/mcp-server_darwin_arm64.tar.gz"
      sha256 "9dcee3b30b0d066190dead75fbb0c90affc2f2313048550a2668fe5a40778355"

      define_method(:install) do
        bin.install "mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.1.14/mcp-server_linux_amd64.tar.gz"
      sha256 "5584f2a90d631d9168566497ccd97f52ce9d8186fba08510807a9702f3197aaf"
      define_method(:install) do
        bin.install "mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/mcp-server/releases/download/v0.1.14/mcp-server_linux_arm64.tar.gz"
      sha256 "893adec205c941dd3ae7e84dd37aebe0c9accc676c3e1dc33de7252a2c620151"
      define_method(:install) do
        bin.install "mcp-server"
      end
    end
  end

  test do
    assert_match "tinysystems", shell_output("#{bin}/mcp-server --help 2>&1", 0)
  end
end
