# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tiny < Formula
  desc "Self-hosted AI agents on your own Kubernetes"
  homepage "https://tinysystems.io"
  version "0.5.37"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiny-systems/tiny/releases/download/v0.5.37/tiny_0.5.37_darwin_amd64.tar.gz"
      sha256 "f1af44ab3a99590d931d1214183a0c7a3d0802db4ed6bccd1b85a47636b54677"

      define_method(:install) do
        bin.install "tiny"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiny-systems/tiny/releases/download/v0.5.37/tiny_0.5.37_darwin_arm64.tar.gz"
      sha256 "d919d15f879544e62cb496a88a4697518a99395558afa98a6f9f76fce1d60453"

      define_method(:install) do
        bin.install "tiny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/tiny/releases/download/v0.5.37/tiny_0.5.37_linux_amd64.tar.gz"
      sha256 "df09f77757c201568c95d8f94df730df80eb644d745ca5fcc9ca4a4f31ed6afc"
      define_method(:install) do
        bin.install "tiny"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiny-systems/tiny/releases/download/v0.5.37/tiny_0.5.37_linux_arm64.tar.gz"
      sha256 "9c2b05fae7bab57bfeeead58b4aa5cc571c6edbb256ae316830cba283f963505"
      define_method(:install) do
        bin.install "tiny"
      end
    end
  end

  test do
    system "#{bin}/tiny", "--version"
  end
end
